# Site Settings

# import theme
theme: jekyll-theme-chirpy

# Only if your site type is Github Pages project and there is no custom domain name, modify the value below to '/project name'.
baseurl: ''

# The language of the site › https://www.w3.org/International/questions/qa-choosing-language-tags
# If a file with the same name exists in the folder `_data/locales`, the layout language will also change,
# Otherwise, the default value of 'en' is used for the layout language.
lang: en

# Additional parameters for time localization, optional. › https://github.com/iamkun/dayjs/tree/dev/src/locale
prefer_datetime_locale:

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: America/Los_Angeles

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
title: sudomaze       # main title

tagline: thinking out loud   # subtitle

description: >-                        # Used by seo meta and atom feeds
  Personal blog of Mazen Alotaibi

# Fill in the protocol and domain name of your website, for example, 'https://username.github.io'
url: 'https://sudomaze.dev'

author: Mazen Alotaibi    # full name

github:
  username: sudomaze

linkedin:
  username: sudomaze     # Github username

# twitter:
#   username: sudomaze       # Twitter username

# myanimelist:
#   username: sudomaze

# I am using Notion page for my weekly logs
weeklylogs:
  username: sudomaze

goodreads:
  username: sudomaze
social:
  name: Mazen Alotaibi                  # will appear as the copyright holder in the footer
  email: sudomaze@gmail.com             # email address
  links:
    # The first link will be the copyright owner's link
    - https://sudomaze.dev/
    # - https://twitter.com/sudomaze      #twitter homepage
    - https://github.com/sudomaze       # Github homepage
    # uncomment to add more links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/sudomaze

google_site_verification:       # fill in your verification string

# ↑ --------------------------
# `jekyll-seo-tag` setup ends

# Customize Iconfont's icon link. › https://www.iconfont.cn/
# If you need to add your own Iconfont icon, please create a new project in Iconfont,
# Add the icon to the project, select Font Class, view the online link, and copy it below.
#
# Note: Please do not have the same name as the icon originally used by the project, please search globally to ensure that the name is not used.
# A better way is to modify the FontClass/Symbol prefix of the Iconfont project to another value.
iconfont_css:
  # This css contains icons prefixed with 'icon-', which are the core icons of the template, do not delete.
  - //at.alicdn.com/t/font_2440352_86vrobdp9vu.css
  # This css contains icons prefixed with 'icon-nihil-', the icons used for my blog content, which can be removed.
  - //at.alicdn.com/t/font_2451185_tgvgeuen2lh.css
  # Add your Iconfont icon link
  - //cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css

google_analytics:
  id: 'G-RK9LRGVP0T'              # Fill in your Google Analytics ID
  # Google Analytics Page Views Settings
  pv:
    proxy_endpoint:   # Fill in Google App Engine's Google Analytics superProxy endpoint
    cache_path:       # pv data local cache, good for people in GFW area

# Set preferred color scheme
#
# Tip: Leave blank to follow the system's default preferred color scheme and appear at the bottom of the sidebar
# A button to switch between light and dark themes.
#
# Available options:
#
# light - use a light color scheme
# dark - use a dark color scheme
#
theme_mode:   # [light|dark]

# Image CDN endpoint.
# Note that once assigned, the CDN URL will be added to all image (website avatar and post images) paths.
# For example, 'https://cdn.com'
img_cdn: ''

# Sidebar avatar, supports local or CROS resources
avatar: /avatar.png

# Set the content to display the right sidebar
panel:
  # Set the content displayed in the right sidebar of the post
  #
  # hint:
  # The corresponding block must not be displayed when the global switch is false.
  # When the global switch is true, you can use the form in the header of the md file of the post:
  #      lastmod: false
  # way to turn off the function of the right sidebar for this post.
  post:
    # latest update
    lastmod: true
    # Popular tags
    trending_tags: false
    # external link
    external_links: true
    # content
    toc: true

comments:
  active: 'disqus'  # Post comment area global switch, for example, 'disqus'. Leave empty to disable
  # active option can be as follows:
  # disqus comment system > https://disqus.com/
  disqus:
    shortname:    # fill in your disqus shorname › https://help.disqus.com/en/articles/1717111-what-sa-shortname
  # utterances comment system › https://utteranc.es/
  utterances:
    repo:         # <Github username>/<repo name>
    issue_term:   # <link|path|title|...>
  # Valine Comment System › https://valine.js.org/
  valine:
    leancloud_appid:    # Enter your LeanCloud App ID
    leancloud_appkey:   # Enter your LeanCloud App Key
    placeholder: "Say something! PS: Enter the QQ number in the nickname column to automatically obtain the QQ nickname and QQ avatar~" # Text displayed when the comment box is blank
    avatar: mp          # default avatar › https://valine.js.org/avatar.html
  # Waline comment system is an improved version of Valine, with a backend and more secure. › https://waline.js.org/
  waline:
    server: https://myblog-comments.vercel.app/    # Vercal server address
    placeholder: 说点什么吧！    # Text to display when the comment box is blank
    avatar: mp          # default avatar › https://waline.js.org/guide/client/avatar.html
  # Giscus Options › https://giscus.app
  giscus:
    repo:             # <Github username>/<repo name>
    repo_id:
    category:
    category_id:
    mapping:          # optional, defaults to 'pathname'
    input_position:   # optional, default is 'bottom'
    lang:             # optional, defaults to the value of `site.lang`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled:  false    # boolean, leave empty to indicate no
    # Specify the Jekyll environment, empty means both are enabled
    # Only takes effect when `assets.self_host.enabled` is 'true'
    env:         # [development|production]

# number of posts per page
paginate: 10

# ------------ The following settings are not recommended to be modified-------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge settings › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''          # empty string means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments on posts
      # Default display of the right sidebar
      lastmod: true
      trending_tags: true
      external_links: true
      toc: true
      # don't change it unless you're an expert in Jekyll and web development,
      # Or you think you're smart enough to modify this template to some other relative path.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # See `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
